plugins {
    id 'java'
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":common")

    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'com.auth0:java-jwt:4.4.0'

}

test {
    useJUnitPlatform()
}
tasks.named('jar') {
    enabled = false  // plain jar 비활성화
}

tasks.named('bootJar') {
    enabled = true   // bootJar 활성화
}