plugins {
    id 'java'
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-server'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

}

test {
    useJUnitPlatform()
}
tasks.named('jar') {
    enabled = false  // plain jar 비활성화
}

tasks.named('bootJar') {
    enabled = true   // bootJar 활성화
}
