plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.coupon'
version = '0.0.1-SNAPSHOT'

allprojects {
	version = '0.0.1-SNAPSHOT'

	repositories {
		mavenCentral()
	}
}

subprojects {
	group = 'com.coupon'

	apply plugin: 'java'
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'
	apply plugin: 'java-test-fixtures'

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(17)
		}
	}


	configurations {
		compileOnly {
			extendsFrom annotationProcessor
		}
	}
	ext {
		set('springCloudVersion', "2023.0.0")
	}

	dependencyManagement {
		imports {
			mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
		}
	}

	dependencies {
	}

	bootJar { enabled = false }
	jar { enabled = true }

	tasks.named('test') {
		useJUnitPlatform()
	}
}
project(':member-service') {
	dependencies {
		implementation project(':common')
	}
}

project(':store-service') {
	dependencies {
		implementation project(':common')
	}
}

project(':coupon-service') {
	dependencies {
		implementation project(':common')
	}
}

project(':order-service') {
	dependencies {
		implementation project(':common')
	}
}

project(':payment-service') {
	dependencies {
		implementation project(':common')
	}
}
