
services:
  order-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8084:8084
    networks:
      - coupons-network
#    environment:
#      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka-server:9092

  # MySQL 서비스
  order-mysql:
    image: mysql:latest
    container_name: order-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3310:3306"
    volumes:
      - /Users/jeongjuhyeon/개발/docker-mysql/mysql_data_order:/var/lib/mysql
    networks:
      - coupons-network
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 5
      start_period: 30s
  order-mongodb:
    image: mongo:latest
    container_name: order-mongodb
    ports:
      - "27017:27017"
    volumes:
      - /Users/jeongjuhyeon/개발/docker-mongo/mongo_data:/var/lib/db
    networks:
      - coupons-network

#  mysqld-exporter:
#    container_name: mysqld_exporter
#    image: prom/mysqld-exporter
#    environment:
#      - DATA_SOURCE_NAME="wngus:password123@(order-mysql:3306)/"
#    command:
#      - "--mysqld.username=wngus:password123"
#      - "--mysqld.address=order-mysql:3306"
#    ports:
#      - "9104:9104"
#    depends_on:
#      - order-mysql
#    restart: unless-stopped
#    networks:
#      - coupons-network  # 추가된 부분
#
#
##  # Prometheus 서비스
##  prometheus:
##    image: prom/prometheus:latest
##    container_name: prometheus
##    volumes:
##      - ./prometheus.yml:/etc/prometheus/prometheus.yml
##    command:
##      - '--enable-feature=native-histograms'
##      - '--web.enable-remote-write-receiver'
##      - '--config.file=/etc/prometheus/prometheus.yml'
##    ports:
##      - "9090:9090"
##    networks:
##      - coupons-network
#
#  # Grafana 서비스
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    networks:
#      - coupons-network

networks:
  coupons-network:
    external: true


















