server:
  port: 8082

spring:
  application:
    name: storeserver
  datasource:
    url: jdbc:mysql://store-mysql:3306/store?rewriteBatchedStatements=true
    username: root
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 55

  data:
    redis:
      cluster:
        nodes:
          - redis-node-1:6379
          - redis-node-2:6379
          - redis-node-3:6379
          - redis-node-4:6379
          - redis-node-5:6379
          - redis-node-6:6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 200
    open-in-view: false

  kafka:
    bootstrap-servers: kafka-server:9092
    consumer:
      properties:
        spring.json.trusted.packages: "*"
jwt:
  secret:
    key: 605dce51-77ff-44a4-8977-423ec21b9e0c

logging.level:
  org:
  hibernate.SQL: debug
  springFramework:
    transaction:
      interceptor : TRACE

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

resilience4j:
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 5
        max-wait-duration: 0
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 10s
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 0
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
    instances:
      member-service:
        base-config: default
